---
kind: pipeline
type: docker
name: docker-build-push

platform:
  os: linux
  arch: amd64

steps:

- name: Scan with WIZCLI
  image: wiziocli.azurecr.io/wizcli:latest
  environment:
    WIZ_POLICY: imsed-mis-policy
    WIZ_CLIENT_ID:
      from_secret: WIZ_CLIENT_ID
    WIZ_CLIENT_SECRET:
      from_secret: WIZ_CLIENT_SECRET
  commands:
    - echo $WIZ_CLIENT_ID
    - /entrypoint auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET 
    - /entrypoint iac scan --path ./ -p $WIZ_POLICY  --secrets=false
